### ISSUE TITLE
Scan AWS resources with one auth assuming multiple roles

### ISSUE THREAD

**Issue by wbeuil** [snyk/driftctl#1177] opened 2021-10-26 15:21 UTC
**Description**
driftctl should be able to scan resources with one user assuming multiple roles. 

```hcl
provider "aws" {
  alias = "ec2"
  region  = "us-east-2"
  assume_role {
    role_arn     = "arn:aws:iam::XXX:role/ec2_assume_role"
    session_name = "ec2-terraform"
  }
}

provider "aws" {
  alias = "sqs"
  region  = "us-east-2"
  assume_role {
    role_arn     = "arn:aws:iam::XXX:role/sqs_assume_role"
    session_name = "sqs-terraform"
  }
}

resource "aws_instance" "foo" {
  provider = aws.ec2
  ami           = "ami-074cce78125f09d61"
  instance_type = "t2.micro"
  availability_zone = "us-east-2a"
}

resource "aws_sqs_queue" "foo" {
  provider = aws.sqs
  name = "foo"
}
```

Terraform is initiating 2 different providers (one with ec2_assume_role, and the other with sqs_assume_role) and they tag which resources need one provider over the other.

**Comment by eliecharra** [comment] 2022-01-07 10:53
Duplicate of #1173

**Closed by eliecharra** 2022-01-07 10:53 UTC
Labels: kind/bug, need-triage
