### ISSUE TITLE
False positive on timeouts attribute in aws_route_table

### ISSUE THREAD

**Issue by wbeuil** [snyk/driftctl#1500] opened 2022-05-24 11:42 UTC
**Description**
One user found a useless `timeouts` block in its scan for `aws_route_table` resource. We should ignore it to avoid false positive drifts.

**How to reproduce**
Create a `aws_route_table` with a timeouts block.

**Possible Solution**
```go
func initAwsRouteTableMetaData(resourceSchemaRepository resource.SchemaRepositoryInterface) {
	resourceSchemaRepository.SetNormalizeFunc(AwsAmiResourceType, func(res *resource.Resource) {
		val := res.Attrs
		val.SafeDelete([]string{"timeouts"})
	})
}
```

**Comment by karniwl** [comment] 2022-06-28 14:32
for some reason the issue isn't tagged with the PR https://github.com/snyk/driftctl/pull/1545? @chdorner-snyk is this resolved?

**Comment by craigfurman** [comment] 2022-06-29 09:24
Please reopen if this isn't indeed resolved by #1545

**Closed by craigfurman** 2022-06-29 09:24 UTC
Labels: good first issue, kind/bug, status/backlog
